[package]
name = "wst"
description = "a tool for working with websockets"
repository = "https://github.com/wridgers/wst"
readme = "README.md"
version = "0.1.2"
authors = ["Will Ridgers <will@mindfuzz.net>"]
license = "MIT"

[dependencies]
ws = "0.7.3"
getopts = "0.2.15"
